version: '3.8'
services:
  nodejs-barcode:
    build:
      context: ./
      target: production
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "4001:4001"
    environment:
      NODE_ENV: production
